added axios and .env file
Mary321Mary/posleurokov-front-end pull request #1
Opened 2022-07-13 09:41 UTC by Mary321Mary

2022-07-13 09:48 UTC, NikolayRaskin requested changes
good change!
Давай добавим пример работы axios экземпляра

2022-07-13 09:48 UTC, NikolayRaskin commented on posleurokov-app/.env
> +REACT_APP_BASE_URL=
Не думаю что REACT_APP здесь уместно, лучше уже AXIOS_BASE_URL

2022-07-13 09:48 UTC, NikolayRaskin commented on posleurokov-app/src/plugins/axios.js
> +    baseURL: process.env.REACT_APP_BASE_URL
Предлагаю в это PR добавить пример использования axios, нужно сделать интерфейс по которому и будут строиться все запросы в проекте, к тому же протестить env.

2022-07-13 17:21 UTC, Mary321Mary commented on posleurokov-app/src/plugins/axios.js
> +    baseURL: process.env.REACT_APP_BASE_URL
Добавила пример использования axios и протестировала. Запрос и файл .env работают

2022-07-14 06:18 UTC, NikolayRaskin requested changes
well done!
Давай писать функциональные компоненты с хуками

2022-07-14 06:18 UTC, NikolayRaskin commented on posleurokov-app/src/App.js
> +class App extends React.Component {
Давай лучше писать на функциональных компонентах с хуками!

2022-07-14 06:18 UTC, NikolayRaskin commented on posleurokov-app/src/plugins/axios.js
> +            }).then(response => {
что то я совсем не понял зачем к await дописывать then, ты точно понимаешь как работает оператор async/await?

2022-07-14 10:36 UTC, Mary321Mary commented on posleurokov-app/src/App.js
> +class App extends React.Component {
Переделала

2022-07-14 10:36 UTC, Mary321Mary commented on posleurokov-app/src/plugins/axios.js
> +            }).then(response => {
Переделала

2022-07-14 11:55 UTC, NikolayRaskin approved these changes
good change !

2022-07-14 11:56 UTC, merged