Add lesson infopanel and modal
Mary321Mary/posleurokov-front-end pull request #32
Opened 2022-08-19 14:38 UTC by GervantFromRibli

Добавил панель справа от описания занятия с кнопками для подписки и т.д., а также добавил модальное окно. Нужно вставить внутрь компонент, а также передать метод изменения показателя отображения окна.

2022-08-22 08:27 UTC, NikolayRaskin requested changes

2022-08-22 08:27 UTC, NikolayRaskin commented on posleurokov-app/src/plugins/axios.js
> +            'Authorization': `Bearer ${token}`,
а зачем тут токен?

2022-08-22 12:49 UTC, GervantFromRibli commented on posleurokov-app/src/plugins/axios.js
> +            'Authorization': `Bearer ${token}`,
Чтобы подписаться. Нужны же данные человека, который подписывается. Да и нужно предусмотреть защиту, чтобы один не мог подписать другого

2022-08-23 07:22 UTC, NikolayRaskin commented on posleurokov-app/src/plugins/axios.js
> +            'Authorization': `Bearer ${token}`,
я к тому что лучше сделать на уровне axios instance, что бы каждый раз не сетать это токен

2022-08-23 07:22 UTC, NikolayRaskin commented on posleurokov-app/src/plugins/axios.js
> +            'Authorization': `Bearer ${token}`,
поднимать токен из куков

2022-08-23 07:23 UTC, NikolayRaskin commented on posleurokov-app/src/plugins/axios.js
> +            'Authorization': `Bearer ${token}`,
и кстати для этого не обязательно использовать стороннюю библиотеку, код полностью запускается на клиенте

2022-08-23 07:51 UTC, merged