fix style of categories
Mary321Mary/posleurokov-front-end pull request #4
Opened 2022-07-21 19:19 UTC by Mary321Mary

2022-07-25 09:51 UTC, NikolayRaskin requested changes
Well done

2022-07-25 09:51 UTC, NikolayRaskin commented on posleurokov-app/src/pages/Main/Main.jsx
> +                  function(category) {
используй стрелочную функцию

2022-07-25 09:51 UTC, NikolayRaskin commented on posleurokov-app/src/pages/Main/Main.jsx
> +                            function(item) {
используй стрелочную функцию

2022-07-25 09:51 UTC, NikolayRaskin commented on posleurokov-app/src/pages/Main/Main.jsx
> +                function(lesson) {
используй стрелочную функцию

2022-07-25 09:56 UTC, NikolayRaskin requested changes
Good change

2022-07-25 09:56 UTC, NikolayRaskin commented on posleurokov-app/src/components/shared/Categories/Categories.module.scss
> +  padding-top: 60px;
прикалываешься? откуда такие цифры?

2022-07-25 09:56 UTC, NikolayRaskin commented on posleurokov-app/src/pages/Main/Main.jsx
> +                    <div key={lesson.name} style={{
посмотри отступы в дизайне

2022-07-25 18:41 UTC, NikolayRaskin requested changes
Well done.

2022-07-25 18:41 UTC, NikolayRaskin commented on posleurokov-app/src/components/shared/Categories/Categories.module.scss
> +  grid-gap: 20;
нет такого св-ва, тем более с таким значением

2022-07-25 18:41 UTC, NikolayRaskin commented on posleurokov-app/src/components/shared/Categories/Categories.module.scss
> +  display: grid;
вкусовщина, но я бы через flex сделал.
Сразу сделай так что бы при уменьшении экрана, категории перемещались вниз.

2022-07-25 18:41 UTC, NikolayRaskin commented on posleurokov-app/src/components/shared/Category/Category.jsx
>  import logo from '../../../assets/img/art.png';
используй абсолютный импорт, я его добавил в проект
assets/img/art.png -- вот такой путь должен работать

2022-07-25 18:41 UTC, NikolayRaskin commented on posleurokov-app/src/pages/Main/Main.jsx
> +    let lessons = await axiosAPI.getRandomLessons();
почему не const?

2022-07-25 18:41 UTC, NikolayRaskin commented on posleurokov-app/src/pages/Main/Main.jsx
>      let categories = await axiosAPI.getCategories();
почему не const?

2022-07-25 18:41 UTC, NikolayRaskin commented on posleurokov-app/src/pages/Main/Main.jsx
> +                        fontStyle='normal'
fontStyle='normal' можно вообще нигде не прокидывать, он добавлен на body

2022-07-25 18:41 UTC, NikolayRaskin commented on posleurokov-app/src/plugins/axios.js
> +        const response = await instance.get('/api/main-page/categories');
1) Оберни в try/catch и обработай случай ошибки
2) Лучше создать в этой же директории файл, например endpoints.js. Хранить все урлы там, а axios.js их импортировать...
Например 
export const CATEGORIES = '/api/main-page/categories'

2022-07-29 12:08 UTC, GervantFromRibli commented
Я бы все-таки увеличил пустоту между категориями, чтобы было как в фигме, а так ок.
![image](https://user-images.githubusercontent.com/55269575/181755096-3cdbc5b5-dc59-4a87-9a17-c66caa9e8902.png)
![image](https://user-images.githubusercontent.com/55269575/181755120-627e0f33-2daf-417b-9e9f-7026026ef0dd.png)

2022-08-04 09:06 UTC, NikolayRaskin requested changes
А ты уверена что Категории сделаны по дизайну (особенно мобильная часть)

2022-08-04 09:06 UTC, NikolayRaskin commented on posleurokov-app/src/pages/Main/Main.module.scss
> +      align-content: center;
это тут зачем?

2022-08-05 08:28 UTC, merged