Add tabsbar
Mary321Mary/posleurokov-front-end pull request #5
Opened 2022-07-25 08:51 UTC by Mary321Mary

2022-07-25 09:49 UTC, NikolayRaskin requested changes
Good change

2022-07-25 09:49 UTC, NikolayRaskin commented on posleurokov-app/src/components/shared/TabsBar/TabsBar.jsx
> +            dataIndex={i}
а не проще передать индекс в openTab как параметр?

2022-07-25 09:49 UTC, NikolayRaskin commented on posleurokov-app/src/components/shared/TabBarNav/TabBarNav.jsx
> +        dataIndex == activeTab ? styles['tabbutton--active'] : ''
лучше проверять это в Родителе, а сюда передавать пропс уже со значением, isActive

2022-07-25 09:49 UTC, NikolayRaskin commented on posleurokov-app/src/components/shared/TabsBar/TabsBar.jsx
> +const TabsBar = ({ children, ...rest }) => {
он не такой как в дизайне :(

2022-07-25 09:49 UTC, NikolayRaskin commented on posleurokov-app/src/components/test/components-demo/ComponentsDemo.jsx
> +              { title: 'London', content: 'London is the capital city of England.' },
выглядит неплохо, но children это обычно либо html или другие компоненты, предай лучше это через пропс

2022-07-26 05:57 UTC, NikolayRaskin requested changes

2022-07-26 05:57 UTC, NikolayRaskin commented on posleurokov-app/src/components/test/components-demo/ComponentsDemo.jsx
> +    { title: 'Tokyo', count: '10', content: 'Tokyo is the capital of Japan.' },
еще же есть элемент с иконкой )

2022-07-26 05:57 UTC, NikolayRaskin commented on posleurokov-app/src/components/test/components-demo/ComponentsDemo.jsx
>        <Heading tag="h1" center>
tag h1 может быть только 1 на странице

2022-07-27 05:37 UTC, NikolayRaskin requested changes

2022-07-27 05:37 UTC, NikolayRaskin commented on posleurokov-app/src/components/shared/TabBarNav/TabBarNav.jsx
> +        <img src={logo} alt='Все кружки'/>
а почему бы не передавать картинку через пропс?

2022-07-27 05:37 UTC, NikolayRaskin commented on posleurokov-app/src/components/shared/TabBarNav/TabBarNav.module.scss
> +  font-family: 'Roboto-Regular';
Добавляй везде sans-serif

2022-07-27 05:37 UTC, NikolayRaskin commented on posleurokov-app/src/components/shared/TabsBar/TabsBar.jsx
> +            dataIndex={i}
зачем это нужно?

2022-07-29 11:49 UTC, GervantFromRibli commented
Можно в принципе поменять название вкладок, сделать вкладки чуть пошире, как в фигме, и настроить ширину самой плашки с вкладками, чтобы не на всю ширину.
![image](https://user-images.githubusercontent.com/55269575/181752395-18cd3f27-592f-44d6-882c-bb3a36638f6b.png)

2022-08-24 14:59 UTC, NikolayRaskin approved these changes

2022-08-25 09:27 UTC, merged