add responsive for header
Mary321Mary/posleurokov-front-end pull request #6
Opened 2022-07-29 10:21 UTC by Mary321Mary

2022-07-29 11:31 UTC, GervantFromRibli commented
Я бы только сделал пошире расположение элементов (или по центру) и убрал бы серую полоску после номера, а то слишком в глаза бросается, а так ок.
![image](https://user-images.githubusercontent.com/55269575/181749936-3a80eda9-29fb-4085-8aba-12902809c776.png)

2022-08-01 08:19 UTC, NikolayRaskin commented
> Я бы только сделал пошире расположение элементов (или по центру) и убрал бы серую полоску после номера, а то слишком в глаза бросается, а так ок. ![image](https://user-images.githubusercontent.com/55269575/181749936-3a80eda9-29fb-4085-8aba-12902809c776.png)

Это по дизайну!

2022-08-01 13:43 UTC, NikolayRaskin requested changes

2022-08-01 13:43 UTC, NikolayRaskin commented on posleurokov-app/src/components/Header/Header.jsx
> +    if (window.screen.width < 321) {
неееееееет, ты что?
Просто css никакого js для этого

2022-08-04 08:50 UTC, NikolayRaskin requested changes

2022-08-04 08:50 UTC, NikolayRaskin commented on posleurokov-app/src/components/Header/Header.jsx
> +        window.screen.width > 760 ? (
Я же сказал никакого js в рамках работы с шириной экрана, но даже если так, тыы не подписалась на изменение ширины экрана, если уменьшить ширину то нужно в обновить страницу, что бы увидеть адаптивный дизайн
Все в CSS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2022-08-12 14:00 UTC, NikolayRaskin requested changes

2022-08-12 14:00 UTC, NikolayRaskin commented on posleurokov-app/src/components/Header/Header.module.scss
> +  display: flex !important;
не верю что без important тут не обойтись!

2022-08-19 10:09 UTC, NikolayRaskin approved these changes

2022-08-22 11:35 UTC, merged